CREATE TABLE movie (
  id SERIAL PRIMARY KEY NOT NULL,
  title VARCHAR(50) NOT NULL,
  gender VARCHAR(50) NOT NULL
  year VARCHAR(50) NOT NULL,
  firstName VARCHAR(50) NOT NULL
  firstName VARCHAR(50) NOT NULL
);